#mongo-composer.yaml
version: "3.9"
services:
  registry:
    container_name: mongo-eoffice
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    #networks:
    #  - registry-net-front
    #  - registry-net-back
    #environment:
    #  - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
    #  - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    #  #- REGISTRY_AUTH: htpasswd
    #  #- REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #  #- REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - eoffice-mongo-kemenag-01:/data/db
    #  - registry-images-data:/var/lib/registry
    #  - /root/docker/certs:/certs
    #depends_on:
    #  - redis
  #redis:
  #  container_name: redis-registry
  #  image: redis:5
  #  restart: always
  #  ports:
  #    - 6379:6379
  #  networks:
  #    - registry-net-back
  #  volumes:
  #    - registry-redis-data:/data  #redis data

volumes:
  eoffice-mongo-kemenag-01:
    external: true
#  registry-redis-data:
#    external: true
#  registry-images-data:
#    external: true
   
#networks:
#  # The presence of these objects is sufficient to define them
#  registry-net-front:
#    name: registry-net-front
#  registry-net-back:
#    name: registry-net-back

