#docker-compose.yaml

version: "3.9"
services:
  registry:
    container_name: haproxy-eoffice
    image: haproxy-eoffice:1.0.0
    restart: always
    ports:
      - 80:80
    #networks:
    #  - registry-net-front
    #  - registry-net-back
    #environment:
    #  - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
    #  - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    #  #- REGISTRY_AUTH: htpasswd
    #  #- REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #  #- REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #volumes:
    #  - registry-images-data:/var/lib/registry
    #  - /root/docker/certs:/certs
    #depends_on:
    #  - redis
  #redis:
  #  container_name: redis-registry
  #  image: redis:5
  #  restart: always
  #  ports:
  #    - 6379:6379
  #  networks:
  #    - registry-net-back
  #  volumes:
  #    - registry-redis-data:/data  #redis data

#volumes:
#  registry-redis-data:
#    external: true
#  registry-images-data:
#    external: true
   
#networks:
#  # The presence of these objects is sufficient to define them
#  registry-net-front:
#    name: registry-net-front
#  registry-net-back:
#    name: registry-net-back
