#haproxy-svc-nodeport.yaml 
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: roxy-04
    meta.helm.sh/release-namespace: masjid-04
  creationTimestamp: "2021-11-19T01:27:35Z"
  labels:
    app.kubernetes.io/instance: roxy-04
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.7.1
    helm.sh/chart: kubernetes-ingress-1.17.5
  name: roxy-04-kubernetes-ingress
  namespace: masjid-04
  resourceVersion: "280736"
  uid: efe17216-0447-4322-913e-6ea812e1f68d
spec:
  clusterIP: 10.109.29.170
  clusterIPs:
  - 10.109.29.170
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30001
    port: 443
    protocol: TCP
    targetPort: https
  - name: stat
    nodePort: 30002
    port: 1024
    protocol: TCP
    targetPort: stat
  selector:
    app.kubernetes.io/instance: roxy-04
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
